nlftp:
  target: default
  outputs:
    default:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: nlftp
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - spatial
      attach:
        - path: "md:nlftp"
          alias: nlftp
          is_ducklake: true
    local:
      type: duckdb
      path: "md:?motherduck_token={{ env_var('MOTHERDUCK_TOKEN', '') }}"
      database: nlftp
      schema: main
      threads: 4
      extensions:
        - httpfs
        - motherduck
        - ducklake
        - spatial
      attach:
        - path: "md:dev_nlftp"
          alias: nlftp
          is_ducklake: true
